src/ZBlog/Models/Catalog.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace ZBlog.Models
{
    public class Catalog
    {
        public int Id { get; set; }

        [MaxLength(32)]
        public string Url { get; set; }

        public string Title { get; set; }

        public int PRI { get; set; }

        public virtual ICollection<Post> Posts { get; set; } = new List<Post>();
    }
}

src/ZBlog/Controllers/CatalogController.cs
using System.Threading;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using ZBlog.Filters;
using ZBlog.Models;

namespace ZBlog.Controllers
{
    [AdminRequired]
    public class CatalogController : Controller
    {
        private readonly ZBlogDbContext _dbContext;
        private readonly ILogger _logger;
        
        public CatalogController(ZBlogDbContext dbContext, ILogger<CatalogController> logger)
        {
            _dbContext = dbContext;
            _logger = logger;
        }

        // GET: /Catalog
        public async Task<IActionResult> Index(ManageMessageId? message = null)
        {
            ViewData["StatusMessage"] =
                   message == ManageMessageId.CatalogNewSuccess ? "Your catalog has been posted."
                   : message == ManageMessageId.CatalogEditSuccess ? "Your catalog has been updated."
                   : message == ManageMessageId.CatalogDeleteSuccess ? "Your catalog has been deleted."
                   : message == ManageMessageId.Error ? "An error has occurred."
                   : "";

            var catalogs = await _dbContext.Catalogs.Include(c => c.Posts).ToListAsync();

            return View(catalogs);
        }

        // GET: /Catalog/New
        [Route("/Catalog/New")]
        public IActionResult New()
        {
            return View();
        }

        // Post: /Catalog/New
        [HttpPost]
        [Route("/Catalog/New")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> New(Catalog model, CancellationToken requestAborted)
        {
            if (ModelState.IsValid)
            {
                _dbContext.Add(model);
                await _dbContext.SaveChangesAsync(requestAborted);

                _logger.LogDebug($"Added catalog<{model.Title}>");

                return RedirectToAction(nameof(Index), new { Message = ManageMessageId.CatalogNewSuccess });
            }

            return View(model);
        }
        
        // GET: /Catalog/Edit/{id}
        [Route("/Catalog/Edit/{id}")]
        public async Task<IActionResult> Edit(int? id)
        {
            _logger.LogDebug($"Edit catalog<{id}>");

            if (!id.HasValue || id <= 0)
                return BadRequest();

            var catalog = await _dbContext.Catalogs.FirstOrDefaultAsync(c => c.Id == id);

            if (catalog == null)
            {
                return NotFound();
            }

            ViewData["Title"] = $"Catalog Edit<{catalog.Title}>";

            return View(catalog);
        }

        // Post: /Catalog/Edit/{id}
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("/Catalog/Edit/{id}")]
        public async Task<IActionResult> Edit(Catalog model, CancellationToken requestAborted)
        {
            if (ModelState.IsValid)
            {
                _dbContext.Update(model);
                await _dbContext.SaveChangesAsync(requestAborted);

                _logger.LogDebug($"Updated catalog<{model.Title}>");

                return RedirectToAction(nameof(Index), new { Message = ManageMessageId.CatalogEditSuccess });
            }

            return View(model);
        }

        // GET: /Catalog/Delete/{id}
        [Route("/Catalog/Delete/{id}")]
        public async Task<IActionResult> Delete(int? id)
        {
            _logger.LogDebug($"Delete catalog<{id}>");

            if (!id.HasValue || id <= 0)
                return BadRequest();

            var catalog = await _dbContext.Catalogs.FirstOrDefaultAsync(c => c.Id.Equals(id));
            if (catalog == null)
                return NotFound();

            ViewData["Title"] = $"Catalog<{catalog.Title}> Delete Confirmation";

            return View(catalog);
        }

        // POST: /Catalog/Delete/{id}
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("/Catalog/Delete/{id}")]
        public async Task<IActionResult> Delete(int? id, CancellationToken requestAborted)
        {
            if (!id.HasValue || id <= 0)
                return BadRequest();

            var catalog = await _dbContext.Catalogs.FirstOrDefaultAsync(c => c.Id.Equals(id), requestAborted);
            _dbContext.Remove(catalog);
            await _dbContext.SaveChangesAsync(requestAborted);
            _logger.LogDebug($"Deleted catalog<{catalog.Title}>");

            return RedirectToAction(nameof(Index), new { Message = ManageMessageId.CatalogDeleteSuccess });
        }

        #region Helpers

        public enum ManageMessageId
        {
            CatalogNewSuccess,
            CatalogEditSuccess,
            CatalogDeleteSuccess,
            Error
        }

        #endregion
    }
}

src/ZBlog/Views/Catalog/Delete.cshtml
@model Catalog

<h2>@ViewData["Title"]</h2>

<p>
    Are you sure you want to delete the catalog titled
    <strong>@Model.Title</strong>?
</p>

<form asp-controller="Catalog" asp-action="Delete" method="post" class="am-form am-form-horizontal" role="form">
    <hr />
    <div class="am-form-group">
        <button type="submit" class="am-btn am-btn-primary">Delete</button>
        <button type="button" class="am-btn am-btn-secondary" onclick="window.history.go(-1);">Cancel</button>
    </div>
</form>

src/ZBlog/Views/Catalog/Edit.cshtml
@model Catalog

<h2>@ViewData["Title"]</h2>

<form asp-controller="Catalog" asp-action="Edit" method="post" class="am-form am-form-horizontal" role="form">
    <hr />
    <div asp-validation-summary="All" class="am-text-danger"></div>
    <input asp-for="Id" class="am-form-field" type="hidden" />
    <div class="am-form-group">
        <label asp-for="Title" class="am-u-md-2 am-form-label"></label>
        <div class="am-u-md-10">
            <input asp-for="Title" class="am-form-field" placeholder="Title" />
            <span asp-validation-for="Title" class="text-danger"></span>
        </div>
    </div>
    <div class="am-form-group">
        <label asp-for="Url" class="am-u-md-2 am-form-label"></label>
        <div class="am-u-md-10">
            <input asp-for="Url" class="am-form-field" placeholder="Catalog url" />
            <span asp-validation-for="Url" class="text-danger"></span>
        </div>
    </div>
    <div class="am-form-group">
        <label asp-for="PRI" class="am-u-md-2 am-form-label"></label>
        <div class="am-u-md-10">
            <input asp-for="PRI" class="am-form-field" placeholder="Catalog order" />
            <span asp-validation-for="PRI" class="text-danger"></span>
        </div>
    </div>
    <div class="am-form-group">
        <div class="am-u-md-offset-2 am-u-md-10">
            <button type="submit" class="am-btn am-btn-primary">Submit</button>
            <button type="button" class="am-btn am-btn-secondary" onclick="window.history.go(-1);">Cancel</button>
        </div>
    </div>
</form>

src/ZBlog/Views/Catalog/Index.cshtml
@model List<Catalog>
@{
    ViewData["Title"] = "Catalog List";
}

<h2>@ViewData["Title"]</h2>
<p class="am-text-success">@ViewData["StatusMessage"]</p>
<div>
    <table class="am-table am-table-bordered am-table-striped am-table-hover">
        <thead>
            <tr>
                <th>Title</th>
                <th>Url</th>
                <th>PRI</th>
                <th>PostCount</th>
                <th>Manage</th>
            </tr>
        </thead>
        <tbody>
            @foreach (Catalog catalog in Model)
            {
                <tr>
                    <td>@catalog.Title</td>
                    <td>@catalog.Url</td>
                    <td>@catalog.PRI</td>
                    <td>@catalog.Posts.Count</td>
                    <td>
                        <a asp-controller="Catalog" asp-action="Edit" asp-route-id="@catalog.Id">Edit</a>
                        <a asp-controller="Catalog" asp-action="Delete" asp-route-id="@catalog.Id">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

src/ZBlog/Views/Catalog/New.cshtml
@model Catalog

@{
    ViewData["Title"] = "New Catalog";
}

<h2>@ViewData["Title"]</h2>

<form asp-controller="Catalog" asp-action="New" method="post" class="am-form am-form-horizontal" role="form">
    <hr />
    <div asp-validation-summary="All" class="am-text-danger"></div>
    <div class="am-form-group">
        <label asp-for="Title" class="am-u-md-2 am-form-label"></label>
        <div class="am-u-md-10">
            <input asp-for="Title" class="am-form-field" placeholder="Title" />
            <span asp-validation-for="Title" class="text-danger"></span>
        </div>
    </div>
    <div class="am-form-group">
        <label asp-for="Url" class="am-u-md-2 am-form-label"></label>
        <div class="am-u-md-10">
            <input asp-for="Url" class="am-form-field" placeholder="Catalog url" />
            <span asp-validation-for="Url" class="text-danger"></span>
        </div>
    </div>
    <div class="am-form-group">
        <label asp-for="PRI" class="am-u-md-2 am-form-label"></label>
        <div class="am-u-md-10">
            <input asp-for="PRI" class="am-form-field" placeholder="Catalog order" />
            <span asp-validation-for="PRI" class="text-danger"></span>
        </div>
    </div>
    <div class="am-form-group">
        <div class="am-u-md-offset-2 am-u-md-10">
            <button type="submit" class="am-btn am-btn-primary">Submit</button>
            <button type="button" class="am-btn am-btn-secondary" onclick="window.history.go(-1);">Cancel</button>
        </div>
    </div>
</form>